### PR TITLE
Add scripts for speech-to-text using whisper and stt+forced alignment with whisperX

### PR DESCRIPTION
**Pull request by 900miles**
Adds two functions for using Whisper or WhisperX to transcribe an audio file, and can perform speaker diarization and forced alignment of text output if using WhisperX.

### CODE REVIEW

**Comment by fabiocat93** [comment]
hey @900miles do you mind importing the packages you use in your `process.py` file and adding them to the dependencies of the package?

**Comment by 900miles** [comment]
New commit should allow working directly with Audio objects. I've also added a requirements.txt but I've never really made one before so I'm not sure if I did it correctly.

**Comment by satra** [comment]
instead of a requirements.txt just add it to the `pyproject.toml`

**Comment by satra** [comment]
also perhaps change the filename to `speech2text`.

**Comment by 900miles** [comment]
Done and done!

**Pull request merged**
